### ISSUE TITLE
Bug when setting border-radius to 0

### ISSUE THREAD

**Issue by sschottler** [eva-design/eva#72]
If I set `border-radius` to `0` in the json file I use for the `customMapping` property on the `ApplicationProvider` in `@ui-kitten/components`, the generated style sets `borderRadius` to the key `"border-radius"` instead of the expected value of `0`, which throws an error on ios simulator:

`console.error: JSON value 'border-radius' of type NSString cannot be converted to NSNumber`

```json
{
  "strict": {
    "border-radius": 0
  },
  "components": {}
}
```

It could be a problem with these falsy `||` checks in `metaProcessor.ts` file that use the `fallback` parameter, which is the `key`. `MetaProcessor` gets called by `SchemaProcessor.process` which `ApplicationProvider` is using internally to create styles when custom mapping is set.

https://github.com/eva-design/eva/blob/58f41aafb11bfeea83540977f92a7c47b5a695ab/packages/processor/js/src/processor/meta/metaProcessor.ts#L49-L61

**Comment by AntonBorovoi** [comment]
@sschottler Should be resolved by https://github.com/eva-design/eva/pull/87
